<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Aprobar_todos</name>
   <tag></tag>
   <elementGuidId>b89b6e55-d924-4cd7-ae02-9f199825c75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;allbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='allbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d8fedfb-bc2d-4a76-a791-5e148bd2597c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>allbox</value>
      <webElementGuid>8788185a-ce9d-44fb-8876-0ff4909f6491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>32856663-5a1b-4a66-8ff3-c1ff757068ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CheckAll();</value>
      <webElementGuid>840e6977-921c-4a35-ab3f-dddbbe027dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvAjustes&quot;)/tbody[1]/tr[@class=&quot;headerDataGrid&quot;]/th[9]/input[1]</value>
      <webElementGuid>9d0cf0db-7f93-466e-b665-cd621e06dbd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='allbox']</value>
      <webElementGuid>01d1491e-59eb-439f-953f-46922a626a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_gvAjustes']/tbody/tr/th[9]/input</value>
      <webElementGuid>f8128c79-00a8-4769-93c5-428b7be717d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[9]/input</value>
      <webElementGuid>f534b02a-a75a-41ae-9df7-e136cb45ce78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'allbox' and @type = 'checkbox']</value>
      <webElementGuid>61be86d2-17db-4dc0-a0a8-78f8aca3f2a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
