<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PENDIENTE_ctl00ContentPlaceHolder1gvAjustesctl02chkOpciones_adqa</name>
   <tag></tag>
   <elementGuidId>b2c22c95-646e-4a92-879b-7b9650269df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_gvAjustes_ctl02_chkOpciones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_gvAjustes_ctl02_chkOpciones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0f3d03d-e5d9-4ba1-827f-65e40a75498a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_gvAjustes_ctl02_chkOpciones</value>
      <webElementGuid>9f0a347a-03f3-408f-9692-7293195c3fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>38a6c69f-bdbf-4d47-96d8-e6a9cecb87be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$gvAjustes$ctl02$chkOpciones</value>
      <webElementGuid>d93b8512-915c-4adf-8196-1e35ba8f21f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CCheckAll();</value>
      <webElementGuid>0aced43e-25e5-4dcd-8fab-ded0a8a847f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_gvAjustes_ctl02_chkOpciones&quot;)</value>
      <webElementGuid>ea4ed922-dc06-4048-9810-955612391ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_gvAjustes_ctl02_chkOpciones']</value>
      <webElementGuid>783689d7-b208-41fe-ba95-b70e15e425bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_gvAjustes']/tbody/tr[2]/td[9]/input</value>
      <webElementGuid>4241e260-30e0-4325-9471-0e2309d8cc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/input</value>
      <webElementGuid>b331f272-33a0-4381-910c-033b7570ee97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder1_gvAjustes_ctl02_chkOpciones' and @type = 'checkbox' and @name = 'ctl00$ContentPlaceHolder1$gvAjustes$ctl02$chkOpciones']</value>
      <webElementGuid>0765e5fe-c4ec-49bb-a97f-de2ec67f2544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
