<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beneficios_at</name>
   <tag></tag>
   <elementGuidId>8dd0d964-6321-423f-a431-d45216a6d8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MenuLateral_repLista_ctl00_hypLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MenuLateral_repLista_ctl00_hypLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7ac0e7e0-554f-4d93-b6e4-0123ff9af610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MenuLateral_repLista_ctl00_hypLink</value>
      <webElementGuid>6cc4830d-f9f7-40f7-9cbf-1c68b73e4149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Beneficios/</value>
      <webElementGuid>d058631e-2b29-4a1e-a9da-e41e03f0dbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beneficios</value>
      <webElementGuid>616d8a45-ffaf-4ad5-9e39-c451c268dc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuLateral_repLista_ctl00_hypLink&quot;)</value>
      <webElementGuid>09f4d835-6b9b-40e7-b66d-c2300f937f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MenuLateral_repLista_ctl00_hypLink']</value>
      <webElementGuid>147a7fc8-6737-4746-98a0-8389b1c1e73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>90df897e-c99d-4bc6-b4ea-c214299f3346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beneficios')]</value>
      <webElementGuid>630b3ac4-af65-4f95-b188-fd9a7916a1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguridad'])[1]/following::a[1]</value>
      <webElementGuid>560f80db-1f3b-4bec-9fba-2d2da9f071d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventario'])[1]/following::a[2]</value>
      <webElementGuid>01bb8a26-c757-4673-bd3d-b88d338ea2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bloqueo'])[1]/preceding::a[1]</value>
      <webElementGuid>a12854b4-b553-44ff-b8c8-33ce4e860f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cambios Masivos de Perfil'])[1]/preceding::a[2]</value>
      <webElementGuid>4bdec50c-f786-4261-a9b9-ad5e63c268b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beneficios']/parent::*</value>
      <webElementGuid>78069cde-37a0-4a68-a452-aaf1627ff467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Beneficios/')]</value>
      <webElementGuid>ddab2581-bc81-4cd7-a568-7661d1205895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>3d301a82-ca89-4824-9be9-e39365632c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MenuLateral_repLista_ctl00_hypLink' and @href = 'Beneficios/' and (text() = 'Beneficios' or . = 'Beneficios')]</value>
      <webElementGuid>b84a86c1-3596-4421-a993-1809b73a0460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
