<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Operacin efectuada con xito_btnOk_cpn</name>
   <tag></tag>
   <elementGuidId>5345e7fd-ae09-46f0-a800-4f0dd31c0037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnOk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnOk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a105b65-c435-498b-bc81-9b4816d952bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5f42a768-67b7-47c6-8dc3-1323ca4dc6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnOk</value>
      <webElementGuid>46dd6efe-4813-40fe-a1d4-95361bdf6a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>07c0d896-8dcb-4493-8028-d907e57cf9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnOk</value>
      <webElementGuid>cba8f65f-79cc-4d85-a8f8-2d09cc6971c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnOk&quot;)</value>
      <webElementGuid>568fb83d-868d-4ce2-93e3-9fd54d8a3c94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnOk']</value>
      <webElementGuid>cedcdff9-37f3-44e4-a0fe-56f07bf7142b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>fac71e95-c329-4cf4-94b2-f7bef9325400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>9048434e-8cd0-4bec-b6f4-0b6c483eee8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnOk' and @id = 'btnOk']</value>
      <webElementGuid>c915cad6-d459-4655-a7eb-9d6ffa0411ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
