<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Administracin_bv</name>
   <tag></tag>
   <elementGuidId>252f3c94-525b-4ff4-bb76-740d733f868c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_Header1_repModulos_ctl00_hypLink']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>7777bf48-4b1c-41b4-864b-e9b5de540ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administración</value>
      <webElementGuid>3bea6db9-5e3a-4fb2-837d-3b272e35833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Header1_repModulos_ctl00_hypLink&quot;)/em[1]</value>
      <webElementGuid>9a179aef-1110-41e1-a128-6161d75bb2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_Header1_repModulos_ctl00_hypLink']/em</value>
      <webElementGuid>83e36918-94aa-4de4-bfb3-b6b79ca632eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x Salir'])[1]/following::em[1]</value>
      <webElementGuid>b253a712-7b70-4656-b7bb-fe9c530b876d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRANK FLOREZ'])[1]/following::em[1]</value>
      <webElementGuid>9781cc36-d99d-4359-93f3-eff5d8cf53fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adquisición'])[1]/preceding::em[1]</value>
      <webElementGuid>8dbdc1a1-94e5-4915-add1-c196a403fc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención'])[1]/preceding::em[2]</value>
      <webElementGuid>0feb8a3d-7bcc-47d1-a728-06e9d7671de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administración']/parent::*</value>
      <webElementGuid>7978a78f-8383-4e64-b15a-fd5f98c661b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>65573991-8de3-4b26-9dad-0a7473c656c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Administración' or . = 'Administración')]</value>
      <webElementGuid>2eea9805-a71b-4afb-b94b-9fab0b6ff387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
