<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Seguridad_atcex</name>
   <tag></tag>
   <elementGuidId>977d2cf6-e0cc-4a7d-8ba5-b8bd2b9594e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_Header1_repModulos_ctl07_hypLink > em</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_Header1_repModulos_ctl07_hypLink']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>6b2e24e4-e8e8-49c5-a35f-34e9978765d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seguridad</value>
      <webElementGuid>143f0c69-ec97-44e6-84f9-19e5f2e29331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Header1_repModulos_ctl07_hypLink&quot;)/em[1]</value>
      <webElementGuid>613b9516-bdba-4557-86f5-fa183f9382e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_Header1_repModulos_ctl07_hypLink']/em</value>
      <webElementGuid>4d9b11e7-9cfa-44aa-ad44-1a4d1e0ced10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventario'])[1]/following::em[1]</value>
      <webElementGuid>07106053-504c-4419-b13d-399d97b663c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emisión'])[1]/following::em[2]</value>
      <webElementGuid>712e736f-64aa-4e73-a1f2-f26c39fb5274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficios'])[1]/preceding::em[1]</value>
      <webElementGuid>626a7b8b-b6e6-4d3f-9220-b1da6a9b08c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bloqueo'])[1]/preceding::em[1]</value>
      <webElementGuid>34779966-c397-4bb2-ac2b-504c7c682308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seguridad']/parent::*</value>
      <webElementGuid>13ff9b37-2322-4937-b221-803374fc390d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/em</value>
      <webElementGuid>2a3ad0c5-c45f-44b1-ad02-a5455a7a5f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Seguridad' or . = 'Seguridad')]</value>
      <webElementGuid>f39ba608-45b8-4b63-8573-6efeaea8f1af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
