<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Red de Recarga Externa_adq</name>
   <tag></tag>
   <elementGuidId>f7c57b82-18af-4f35-b9f3-2608d08027ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MenuLateral_repLista_ctl07_hypLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MenuLateral_repLista_ctl07_hypLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63c14680-ce02-4ef8-806a-b3ce3666d6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MenuLateral_repLista_ctl07_hypLink</value>
      <webElementGuid>799f2145-8aa7-48b3-bafb-4b94c1661506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>RedDeRecargaExterna/</value>
      <webElementGuid>08b3b822-6855-4769-a273-3da869d26f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Red de Recarga Externa</value>
      <webElementGuid>087e9ec6-fb30-4ad4-823a-bd81c126c7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuLateral_repLista_ctl07_hypLink&quot;)</value>
      <webElementGuid>4e134cb9-cdfb-4fff-903f-8c447359066a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MenuLateral_repLista_ctl07_hypLink']</value>
      <webElementGuid>b9b3ae99-2595-4feb-b5fe-81d656dee547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[8]/td/a</value>
      <webElementGuid>17177e88-84e1-4594-af64-ea8183f95006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Red de Recarga Externa')]</value>
      <webElementGuid>9e789f67-2498-4e95-9122-7dd4321130f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punto de Venta'])[1]/following::a[1]</value>
      <webElementGuid>903108fc-235c-46f7-b518-47c096260443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoreo'])[1]/following::a[2]</value>
      <webElementGuid>2bd7a7a4-53ea-4b6f-91d6-b0aa5a3748cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Red de recarga Virtual'])[1]/preceding::a[1]</value>
      <webElementGuid>16ade072-57c3-4439-85be-8b82c446bf01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registros'])[1]/preceding::a[2]</value>
      <webElementGuid>4e096e3b-01ca-4ebb-9e9d-6b6187bdb03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Red de Recarga Externa']/parent::*</value>
      <webElementGuid>29d3b7bf-7100-4b57-a7cc-77cb13115187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'RedDeRecargaExterna/')]</value>
      <webElementGuid>95969400-4489-42fe-995e-7085169ccfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a</value>
      <webElementGuid>a1f53b9f-278c-4e81-b989-0583c08f0a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MenuLateral_repLista_ctl07_hypLink' and @href = 'RedDeRecargaExterna/' and (text() = 'Red de Recarga Externa' or . = 'Red de Recarga Externa')]</value>
      <webElementGuid>97f9621f-a2c8-465f-b093-f1582ece1a94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
