<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cvica Transaccional_ad</name>
   <tag></tag>
   <elementGuidId>19e88e44-8db8-4c35-adf6-2a5d6274eed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MenuLateral_repLista_ctl00_hypLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MenuLateral_repLista_ctl00_hypLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f4d8c13-7cdc-4df9-89f2-cf3576312aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MenuLateral_repLista_ctl00_hypLink</value>
      <webElementGuid>89863b9b-e4ee-4cdd-aac9-a4efd3006061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>CivicaTransaccional/</value>
      <webElementGuid>07a3c4e7-9753-4df1-acd5-c0d3274dc642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cívica Transaccional</value>
      <webElementGuid>19215e09-9b74-472b-af55-3eb0ab6d8819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuLateral_repLista_ctl00_hypLink&quot;)</value>
      <webElementGuid>398b12ce-47d0-4f6b-bedf-12834151c301</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MenuLateral_repLista_ctl00_hypLink']</value>
      <webElementGuid>f7259ca1-eb63-4735-a2ab-3447f12f90c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>e4c94536-37cc-40e4-b8b7-ea54e0e1304d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cívica Transaccional')]</value>
      <webElementGuid>90445970-a334-4bd8-ad23-a877506dd859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguridad'])[1]/following::a[1]</value>
      <webElementGuid>3e43da6f-913e-4ff8-b4ad-232a2a03318d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventario'])[1]/following::a[2]</value>
      <webElementGuid>81f536d8-889c-484f-bb5f-9d16e95573d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Políticas de Integración'])[1]/preceding::a[1]</value>
      <webElementGuid>26a9e067-f99d-4d15-a96c-f1d907a91fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registros'])[1]/preceding::a[2]</value>
      <webElementGuid>d2318e9d-6753-425f-b9d6-7022ad93f3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cívica Transaccional']/parent::*</value>
      <webElementGuid>e84f25a1-f5fe-429b-90e5-c00085c40784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'CivicaTransaccional/')]</value>
      <webElementGuid>8357eaf6-a4b6-461b-8359-d67c031b350c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>488889fb-c39c-4291-b623-d01ce05ba28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MenuLateral_repLista_ctl00_hypLink' and @href = 'CivicaTransaccional/' and (text() = 'Cívica Transaccional' or . = 'Cívica Transaccional')]</value>
      <webElementGuid>937e2275-be50-4d75-9aaf-8be080eeda00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
