<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Administracin_ad</name>
   <tag></tag>
   <elementGuidId>13658163-ed2f-49a9-afbd-4ebf1dff93d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_Header1_repModulos_ctl00_hypLink']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>2ddac2ee-bb64-46fc-972d-75111995ffcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administración</value>
      <webElementGuid>adc62d76-c9b7-4710-88b9-bac0fbb8a120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Header1_repModulos_ctl00_hypLink&quot;)/em[1]</value>
      <webElementGuid>7ce898dc-0a03-440f-b962-1d819807438a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_Header1_repModulos_ctl00_hypLink']/em</value>
      <webElementGuid>5f980c30-4ead-438d-ad26-7a1ff35fd5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x Salir'])[1]/following::em[1]</value>
      <webElementGuid>099b06db-f10a-4355-ad98-5d7f32b39286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRANK FLOREZ'])[1]/following::em[1]</value>
      <webElementGuid>c12a42ea-a7e6-4365-898d-a2ee7f4266fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adquisición'])[1]/preceding::em[1]</value>
      <webElementGuid>c7e28d3b-c3c1-4d72-bf94-f7907c6ecd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención'])[1]/preceding::em[2]</value>
      <webElementGuid>4d715b11-b9c6-46a3-9c44-c996e8dc94bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administración']/parent::*</value>
      <webElementGuid>1e464232-2048-4c66-9661-19ab0d4bc810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>368b1dea-02f8-4fab-b067-0f30cb692018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Administración' or . = 'Administración')]</value>
      <webElementGuid>cb5e37e1-a18b-43aa-8025-fb8950d8e351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
