<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1.009.010.785_atcexd</name>
   <tag></tag>
   <elementGuidId>7b996f82-0d1d-467a-80ff-71328d940e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_lblSldFis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ContentPlaceHolder1_lblSldFis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d638270-8e34-40c6-860f-7c6dd09a27c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_lblSldFis</value>
      <webElementGuid>305fbd09-e168-4af9-a93d-add498d1920b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1.009.010.785</value>
      <webElementGuid>3d83c52e-f9da-4596-ab9e-cbe7d64ecd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_lblSldFis&quot;)</value>
      <webElementGuid>32a8c475-9fc1-4749-b7a7-33204f4a0d35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentPlaceHolder1_lblSldFis']</value>
      <webElementGuid>c5051b04-b660-48cd-a53e-71051d51238b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_tbSaldo']/tbody/tr[4]/td[2]/span</value>
      <webElementGuid>d9c2b8c1-90ac-4dcc-b97b-28efc3906634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Actual'])[1]/following::span[1]</value>
      <webElementGuid>d304e9a4-e891-4d7c-81c6-82729b4408c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Beneficio'])[1]/following::span[3]</value>
      <webElementGuid>6774b467-7d87-436f-84c9-d09638bf868f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recarga masiva de dinero'])[1]/preceding::span[1]</value>
      <webElementGuid>f51b129f-87ef-4e6e-b4a3-8bacdad00fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1.009.010.785']/parent::*</value>
      <webElementGuid>ae2e7f94-c929-4c00-96ae-b2e59b3c1499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/span</value>
      <webElementGuid>3782dce9-bcf7-42a6-a74a-5521aabd21b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_ContentPlaceHolder1_lblSldFis' and (text() = '1.009.010.785' or . = '1.009.010.785')]</value>
      <webElementGuid>9c618648-7e39-4f80-9d38-dab89293c2c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
