<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>eff2f625-2df9-4f28-acbf-2961e9af982a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick=&quot;javascript:SelecionarUsuario('CIVICA','CC 20212240','12156446', 'EVENTUAL', 'CC 20212240', 'AL PORTADOR', '13'
                                    );&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>641b45a8-0756-49e6-a9e1-2cf517805805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../images/ico_detalhes.gif</value>
      <webElementGuid>45eed124-6acb-468f-8fd3-9166b92bf52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:SelecionarUsuario('CIVICA','CC 20212240','12156446', 'EVENTUAL', 'CC 20212240', 'AL PORTADOR', '13'
                                    );</value>
      <webElementGuid>c6984323-8e9c-4504-9093-ac2129e5d1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gvUsuarios&quot;)/tbody[1]/tr[@class=&quot;linhaDataGrid&quot;]/td[4]/img[1]</value>
      <webElementGuid>e8f785c5-19e1-4a98-ac33-7f63c32ec7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick=&quot;javascript:SelecionarUsuario('CIVICA','CC 20212240','12156446', 'EVENTUAL', 'CC 20212240', 'AL PORTADOR', '13'
                                    );&quot;]</value>
      <webElementGuid>a9f17a31-2cb9-4873-bd21-a7f5d1e08128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gvUsuarios']/tbody/tr[2]/td[4]/img</value>
      <webElementGuid>1e128a69-7721-4879-b0cb-e119d0031a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7c8e1ad8-92f5-4f66-8d6c-1de3dd9181d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../images/ico_detalhes.gif']</value>
      <webElementGuid>4c95bf12-4949-47f7-b2e1-502b644ea375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
