<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ACTIVA</name>
   <tag></tag>
   <elementGuidId>755aa5c8-7e5e-45db-9cb4-0980922e65f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_lblStatusTarjeta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctl00_ContentPlaceHolder1_lblStatusTarjeta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2a88ff0a-0000-4f30-b0ea-2ed00bb2f150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_lblStatusTarjeta</value>
      <webElementGuid>feadc104-11f5-46d8-9486-b3e08948bc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACTIVA</value>
      <webElementGuid>78d6f26c-53cf-4f25-a23c-b3ebc96bae23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_lblStatusTarjeta&quot;)</value>
      <webElementGuid>79adfc88-a235-4dea-9eea-936a5b9a4659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_ContentPlaceHolder1_lblStatusTarjeta']</value>
      <webElementGuid>9838fc72-ea1c-4001-9611-c74e1d2b692a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_tbSaldo']/tbody/tr/td[4]/span</value>
      <webElementGuid>543dd52c-1ed9-46ac-8375-105158b33aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Situación'])[2]/following::span[1]</value>
      <webElementGuid>ca53f298-28f1-49ea-b893-337c753a4d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjeta Actual'])[1]/following::span[4]</value>
      <webElementGuid>23e68dd5-932d-4e24-8852-37218418fc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Pendiente por Creditar'])[1]/preceding::span[1]</value>
      <webElementGuid>ae380c20-b2e2-4d9c-8082-b494f505280c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Pendiente por Debitar'])[1]/preceding::span[3]</value>
      <webElementGuid>9643bfd7-6f23-4156-b9f4-97b4a1da5412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACTIVA']/parent::*</value>
      <webElementGuid>43f4faba-0a72-40ba-a8f4-4284eb66dd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[4]/span</value>
      <webElementGuid>536ecc83-9053-48e7-befe-a3ca83094f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_ContentPlaceHolder1_lblStatusTarjeta' and (text() = 'ACTIVA' or . = 'ACTIVA')]</value>
      <webElementGuid>e06d85ac-ebae-43da-b6a0-6351186e5f65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
