<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ajuste de Carga_pdva</name>
   <tag></tag>
   <elementGuidId>ac0e83f3-c983-4b3a-b0cc-768fe28e42d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MenuLateral_repLista_ctl06_repItens_ctl00_hypLinkItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MenuLateral_repLista_ctl06_repItens_ctl00_hypLinkItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7694a6f-5527-4e40-b2da-1aa3a0a3467d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MenuLateral_repLista_ctl06_repItens_ctl00_hypLinkItem</value>
      <webElementGuid>51b2db4e-26d9-4ca3-878b-b44f7c1fc5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>frmAjusteCarga.aspx</value>
      <webElementGuid>20df9c68-1f42-434f-bd69-0aa2c0ef2f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajuste de Carga</value>
      <webElementGuid>60853472-6c8b-42d0-b846-4aeffd15afa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuLateral_repLista_ctl06_repItens_ctl00_hypLinkItem&quot;)</value>
      <webElementGuid>4851352c-f2f2-4cc1-be96-2892e526c4f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MenuLateral_repLista_ctl06_repItens_ctl00_hypLinkItem']</value>
      <webElementGuid>8ca14570-e65b-4f70-8331-d72fefe4c983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[8]/td/a</value>
      <webElementGuid>824b68d3-a572-4a24-bfae-9f5ba2f3158f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ajuste de Carga')]</value>
      <webElementGuid>54397329-aec0-4a1b-a9b8-f5742f25c324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punto de Venta'])[1]/following::a[1]</value>
      <webElementGuid>f8cb789d-ae4a-47aa-9333-36d9d222b443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoreo'])[1]/following::a[2]</value>
      <webElementGuid>a7e81bca-4a9c-4e5a-9f48-75cc276d7a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aprobación Ajuste de Carga'])[1]/preceding::a[1]</value>
      <webElementGuid>50a1f8bd-890f-479c-bd8d-d26ed71220b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autorización'])[1]/preceding::a[2]</value>
      <webElementGuid>bef281f6-48c6-40df-b2bd-7074ac24e9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajuste de Carga']/parent::*</value>
      <webElementGuid>79e66afd-0bea-47f9-a81a-000e148da89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'frmAjusteCarga.aspx')]</value>
      <webElementGuid>d56e3b4c-3d82-4a18-a514-8d1e32005b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a</value>
      <webElementGuid>05ef5bf3-da2f-4294-a93d-69f3dfa3517f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MenuLateral_repLista_ctl06_repItens_ctl00_hypLinkItem' and @href = 'frmAjusteCarga.aspx' and (text() = 'Ajuste de Carga' or . = 'Ajuste de Carga')]</value>
      <webElementGuid>5380e9d1-8170-4f20-ab4d-3b9c57304f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
