<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Administracin_pdva</name>
   <tag></tag>
   <elementGuidId>51235b73-7324-43a3-a221-b578f05993ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_Header1_repModulos_ctl00_hypLink']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>b59e2612-20e3-445b-83fb-4fa26ae35071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administración</value>
      <webElementGuid>c62cd5f2-5bf9-4608-a091-6308049a7e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Header1_repModulos_ctl00_hypLink&quot;)/em[1]</value>
      <webElementGuid>3ca031ec-40c0-4519-9e8c-7a305bd39fd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_Header1_repModulos_ctl00_hypLink']/em</value>
      <webElementGuid>9e19b8e1-a832-4cf8-b7fb-40fac42c24ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='x Salir'])[1]/following::em[1]</value>
      <webElementGuid>0605049b-ab5f-4cc3-a2f2-05f02d83dac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FRANK FLOREZ'])[1]/following::em[1]</value>
      <webElementGuid>cfac8374-69c8-49e3-82ce-3f28b5f7fcd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adquisición'])[1]/preceding::em[1]</value>
      <webElementGuid>eaff0333-6a70-4d41-ac77-8e5ce7fcbe18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atención'])[1]/preceding::em[2]</value>
      <webElementGuid>c6af6a2b-2ddd-4330-aa56-c5bc2e978acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administración']/parent::*</value>
      <webElementGuid>1c28ffc8-270c-4f16-a0ba-fc320fb01d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>a9e1af72-41e9-4230-8aed-5159c8c2966f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Administración' or . = 'Administración')]</value>
      <webElementGuid>2ad07658-8d9a-4ef2-a513-eb5858473064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
