<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>db876b2c-baad-40e4-8702-665bf1450d3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://qabanco.civica.com.co/Civica/images/ico_detalhes.gif')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>08ef76f5-aadc-4d8e-b7ed-24f68e4d9f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qabanco.civica.com.co/Civica/images/ico_detalhes.gif</value>
      <webElementGuid>1627d137-788c-4c29-a141-f5d28dcb9272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/img[1]</value>
      <webElementGuid>d08bea3f-b20c-472c-b530-9ef39c611e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://qabanco.civica.com.co/Civica/images/ico_detalhes.gif')]</value>
      <webElementGuid>6d7aec5e-b64d-4e10-9ba1-ac9706a80810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a800c48b-7980-477c-898a-11e1483ec30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qabanco.civica.com.co/Civica/images/ico_detalhes.gif']</value>
      <webElementGuid>6dc3ddc7-acba-4ba1-aa96-cf787cbd4eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
