<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nm. Tarjeta_txtNumeroTarjeta_cpn</name>
   <tag></tag>
   <elementGuidId>cb5c231c-c130-4a27-949d-3024ab060b01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtNumeroTarjeta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtNumeroTarjeta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdd4587b-6633-42f9-959d-96f25abdb6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtNumeroTarjeta</value>
      <webElementGuid>f8e99c35-1e44-4064-adbd-c2ae3b3059e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9810f646-63d8-4cab-a2e5-c6b7167e76da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>04d9a553-ad68-43b4-836c-82f4ff9a1995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtNumeroTarjeta</value>
      <webElementGuid>40681263-961d-4d04-a44a-929d7db5e82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtNumeroTarjeta&quot;)</value>
      <webElementGuid>2b3772e5-29f1-4443-a0ed-290ba487d493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtNumeroTarjeta']</value>
      <webElementGuid>fea0953d-2a33-4120-ade1-ac4fa19dd78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table[2]/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>53bec647-f0f2-4347-a7b3-431086d58cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>0eb969fd-e922-4700-ba95-383a39ffe99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtNumeroTarjeta' and @type = 'text' and @id = 'txtNumeroTarjeta']</value>
      <webElementGuid>b07db96f-f538-4551-8cd9-ca4acf575096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
