<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REGISTRO BLOQUEADO_btnBuscar_cpn</name>
   <tag></tag>
   <elementGuidId>46bb75b3-cf52-4f03-81cf-a105ebc3be3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnBuscar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnBuscar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77e76fa9-e933-408b-b827-bafd43a458d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a26e8722-d5cf-48c9-94c6-8fbb9c692737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnBuscar</value>
      <webElementGuid>873ab384-ae45-4871-9f0c-1bc5fd384fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>3ba79419-3a49-4a69-94cc-456bf5c1fa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnBuscar</value>
      <webElementGuid>4b8a11f0-64e2-48d6-baa3-addf30c10319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnPersistir</value>
      <webElementGuid>835f758c-82f8-49b2-8dfa-b4fbff882756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnBuscar&quot;)</value>
      <webElementGuid>c5ebd5c6-4f7f-4521-8601-6f5b5f1f2c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnBuscar']</value>
      <webElementGuid>8453861c-56c0-4188-9f34-dbecf61cb156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/table[2]/tbody/tr[5]/td/input</value>
      <webElementGuid>ce591963-d086-4d81-8d51-d9b194d2321c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/input</value>
      <webElementGuid>f5e28c74-933c-434e-9c0e-48533e0028e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnBuscar' and @id = 'btnBuscar']</value>
      <webElementGuid>9912ef59-c372-4231-921b-e10e70bcdb6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
