<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cdula usuario_txtLogin</name>
   <tag></tag>
   <elementGuidId>0d9c8fbf-7aab-4a69-8264-b1c2c9f74608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49c1a70c-eaf7-4a7a-8547-a09a59edc517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtLogin</value>
      <webElementGuid>1ccb2bff-fe1d-445b-ab4c-91e6b30d7227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2711042f-ff35-403c-a8b0-5096dcc4f0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>638f8626-8944-4017-974a-6b5d4b58adc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLogin</value>
      <webElementGuid>14894ee7-afcd-4bc5-b877-a751b9c57be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>a5aaa3dc-9d48-47a2-95a4-84b2c9262bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLogin&quot;)</value>
      <webElementGuid>d704a594-1388-4144-bea2-dcd849297d9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtLogin']</value>
      <webElementGuid>4f5d4e31-8721-474b-9b3a-221b75ef94aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbLogin']/tbody/tr[3]/td/input</value>
      <webElementGuid>538a62c7-28f7-4b54-ab56-6dbecf5133e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>3569190c-61f9-4ecb-b729-da56b3c78590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtLogin' and @type = 'text' and @id = 'txtLogin']</value>
      <webElementGuid>a86e4047-556f-4500-81d9-b30e2ba7161f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
