<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_btnOk</name>
   <tag></tag>
   <elementGuidId>a7d779c5-3643-4b77-a8d8-8eac53250199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnOk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnOk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3654ebf3-f7a5-48d4-b8f9-445dd854b45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a8894bc7-bcef-4b06-90b9-c776e18808e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnOk</value>
      <webElementGuid>3e23649e-f941-4b69-8d2b-1d5a51b5a056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>633a1567-6f0f-40d9-9d32-be96479e4466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>obtenerCliente();</value>
      <webElementGuid>603374b1-6107-4692-b963-4d532a3db98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnOk</value>
      <webElementGuid>7e1bf032-b9cf-4a21-9aa3-2c0616c63fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form2</value>
      <webElementGuid>f728abe5-371c-411a-80bc-615533459d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnOk&quot;)</value>
      <webElementGuid>5a86c61e-8af6-42dd-a42c-c060747a8356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnOk']</value>
      <webElementGuid>8161b3e0-4420-4ded-841a-fda2c76ddd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbLogin']/tbody/tr[5]/td/input[4]</value>
      <webElementGuid>aab04b63-10ac-4614-ab85-070c20ce7add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[4]</value>
      <webElementGuid>db4ce04e-8f08-4e11-b3f0-cbdc9df98f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnOk' and @id = 'btnOk']</value>
      <webElementGuid>5aac2a92-f2cb-40ca-885f-f11b4ef84d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
