<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_txtSena</name>
   <tag></tag>
   <elementGuidId>f1e1642e-c0c2-45a3-80c8-969135c5aa25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtSena</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtSena']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebff8a70-d947-49b1-84a8-22dc911e4677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtSena</value>
      <webElementGuid>c426d45c-94ad-4783-8598-c820b8a816c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a6a8f58f-a3cb-40f4-bcc2-39325c67f74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtSena</value>
      <webElementGuid>6f80b6ef-0986-48a7-9b08-8defaad034bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>ef6b8bb1-2c14-4519-981b-f961e39efb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>IsEnter('btnOk', event);</value>
      <webElementGuid>82292a8c-9e20-4522-9461-abb66b62e53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtSena&quot;)</value>
      <webElementGuid>a4292119-e2fb-4c48-b90d-200fc0f3e7a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtSena']</value>
      <webElementGuid>be59b1c7-4482-48b5-8ed2-17982f827d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbLogin']/tbody/tr[5]/td/input[3]</value>
      <webElementGuid>5329e647-4c91-4a50-a17a-181e8651b96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input[3]</value>
      <webElementGuid>ac635175-904a-46b3-8c27-0f5b2ead9c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtSena' and @type = 'password' and @id = 'txtSena']</value>
      <webElementGuid>a065273c-c171-4815-a3d2-68a5796fd8a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
