<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellidos_ctl00ContentPlaceHolder1btnBuscarUsu_pdvab</name>
   <tag></tag>
   <elementGuidId>bb95640e-8687-486d-9718-f7c78d8db214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_btnBuscarUsu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_btnBuscarUsu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36b599f9-8d3b-4e1a-94aa-5340b898f6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: AbrirPopupPersonaNaturalTarjeta(); __doPostBack('ctl00$ContentPlaceHolder1$btnBuscarUsu','')</value>
      <webElementGuid>5fb9add4-79ec-4a29-acab-dcfe6927d71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$btnBuscarUsu</value>
      <webElementGuid>40f80dca-660f-4f3d-96e5-460b56b4a3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b7cef0a-522b-4d7a-992f-b4ce29245d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_btnBuscarUsu</value>
      <webElementGuid>20207be0-f179-449c-986e-e6ea97aed6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnPersistir</value>
      <webElementGuid>8b660d30-de1f-4626-9c0f-f2cd8e2f9b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>comandname</name>
      <type>Main</type>
      <value>visualizar</value>
      <webElementGuid>3ec8e0bf-3263-473f-8409-634b2d4b0bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>2b96947a-016f-43c1-913e-e0d2ec64cd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationgroup</name>
      <type>Main</type>
      <value>usuario</value>
      <webElementGuid>79ba33d7-3a83-41d9-b534-6a4c7ab4d20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c21ae14a-1ced-4da8-8b76-07d18a970530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_btnBuscarUsu&quot;)</value>
      <webElementGuid>cc313fe6-d1dc-480e-bf67-8f870a5d9d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_btnBuscarUsu']</value>
      <webElementGuid>2660c4a4-5f62-4bdd-9b4c-2f04357010d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[3]/table[2]/tbody/tr/td[5]/input</value>
      <webElementGuid>ecbfd33e-db00-4469-9967-8bd59c9143ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>1a7297f8-346f-4b55-9088-cecb125de312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$btnBuscarUsu' and @type = 'button' and @id = 'ctl00_ContentPlaceHolder1_btnBuscarUsu']</value>
      <webElementGuid>9a7ce682-cf06-42f2-b48e-9f6bceca1016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
