<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Chechk credito</name>
   <tag></tag>
   <elementGuidId>e081c691-fa5d-4a4d-a8c1-02d77b640475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ContentPlaceHolder1_rdbOperacion_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ContentPlaceHolder1_rdbOperacion_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a82b103-fed8-4b93-8cd5-68bcec9b72e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_rdbOperacion_1</value>
      <webElementGuid>7faf28cc-2d2d-4a2c-938d-c4b894cb3822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>36eef1ff-5c49-4c81-a5f5-fc0104a64c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$rdbOperacion</value>
      <webElementGuid>0fd719ac-c4f3-40dc-acb8-79699bfd30a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>C</value>
      <webElementGuid>5e264e78-9a9d-4678-9ebd-0666a9cf907a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>41d47122-c190-46cc-a5d9-ab2d15fe1f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ContentPlaceHolder1_rdbOperacion_1&quot;)</value>
      <webElementGuid>b6500d77-3c5a-48e7-8ef7-c6b6feb5e4c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ContentPlaceHolder1_rdbOperacion_1']</value>
      <webElementGuid>179fd810-92a0-4629-885f-641a28664b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_ContentPlaceHolder1_rdbOperacion']/tbody/tr/td[2]/input</value>
      <webElementGuid>2b7713e2-60f9-4e31-95bc-9c174cd876e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>13dfa476-6a8b-43ab-b858-25da754e73ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_ContentPlaceHolder1_rdbOperacion_1' and @type = 'radio' and @name = 'ctl00$ContentPlaceHolder1$rdbOperacion']</value>
      <webElementGuid>f244fe81-6f14-4944-8da5-b372a7630fce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
