<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Extracto Usuario Cvica_atc</name>
   <tag></tag>
   <elementGuidId>65414c3d-d7ec-423b-9f74-76c358260d1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MenuLateral_repLista_ctl04_repItens_ctl02_hypLinkItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MenuLateral_repLista_ctl04_repItens_ctl02_hypLinkItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edf6c000-72a4-4bd0-bc60-4cb8a68d2522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MenuLateral_repLista_ctl04_repItens_ctl02_hypLinkItem</value>
      <webElementGuid>f7d58458-38f3-4db5-9a29-86dfc7534e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>frmExtractoPNUsuario.aspx</value>
      <webElementGuid>ff4cd933-4598-403e-b2c5-426babeb1dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Extracto Usuario Cívica</value>
      <webElementGuid>41074133-de9a-4aa7-877e-27a7f9009972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuLateral_repLista_ctl04_repItens_ctl02_hypLinkItem&quot;)</value>
      <webElementGuid>16a5a84c-88ae-4489-886a-3d3d259c7ff6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MenuLateral_repLista_ctl04_repItens_ctl02_hypLinkItem']</value>
      <webElementGuid>074632d9-6188-438c-9f42-41d063d841ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[8]/td/a</value>
      <webElementGuid>4ba8e443-f8b3-4134-8422-1e7f9a5b7526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Extracto Usuario Cívica')]</value>
      <webElementGuid>3e82645c-39f7-4400-b1fe-4540d187649e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extracto UL'])[1]/following::a[1]</value>
      <webElementGuid>1af09f1e-7634-4d07-8dc5-d7fdb83ab475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extracto PN'])[1]/following::a[2]</value>
      <webElementGuid>13555623-4114-4353-94f5-7c8f9e1341e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Histórico PN'])[1]/preceding::a[1]</value>
      <webElementGuid>22c498e8-ce5b-4d36-88e3-d6ad56f7914f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sugerencia'])[1]/preceding::a[2]</value>
      <webElementGuid>65e39140-729b-4711-886b-9cccb006d58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Extracto Usuario Cívica']/parent::*</value>
      <webElementGuid>90453410-436d-499e-9c9d-550d9f4792a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'frmExtractoPNUsuario.aspx')]</value>
      <webElementGuid>7cb05d6e-33bf-450c-8ae7-8d9733bd90ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a</value>
      <webElementGuid>689a5975-256d-41f4-8363-e0b7a6d8b7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MenuLateral_repLista_ctl04_repItens_ctl02_hypLinkItem' and @href = 'frmExtractoPNUsuario.aspx' and (text() = 'Extracto Usuario Cívica' or . = 'Extracto Usuario Cívica')]</value>
      <webElementGuid>98ad0434-f654-4955-a438-d1e2b62ddc10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
