<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fidelidad_atc</name>
   <tag></tag>
   <elementGuidId>f27f5144-48f5-4f02-a5d7-e082249736da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MenuLateral_repLista_ctl05_hypLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MenuLateral_repLista_ctl05_hypLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8cbcbfe-c93c-433b-8434-bbbbd345a100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MenuLateral_repLista_ctl05_hypLink</value>
      <webElementGuid>93fe56dc-919d-421f-badf-1a2ab931e00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Fidelidad/</value>
      <webElementGuid>d2271a55-04f1-467b-bda6-d2f85a75463f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fidelidad</value>
      <webElementGuid>e4136429-e363-4a3d-a028-06f0f1f406e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuLateral_repLista_ctl05_hypLink&quot;)</value>
      <webElementGuid>20573523-5fd9-4b2d-8b06-4534b7afe573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MenuLateral_repLista_ctl05_hypLink']</value>
      <webElementGuid>bc2536fb-2d21-4a4c-b45a-d3e76450af1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[11]/td/a</value>
      <webElementGuid>15e86775-6162-476e-b9f8-c5ef9d574310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fidelidad')]</value>
      <webElementGuid>ae7ffc83-dacd-4083-94c1-89655fe138a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sugerencia'])[1]/following::a[1]</value>
      <webElementGuid>54260582-f6f6-480a-aa40-293317616f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Histórico PN'])[1]/following::a[2]</value>
      <webElementGuid>208d0883-6a08-46c1-b375-91cf14a7d2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registros'])[1]/preceding::a[1]</value>
      <webElementGuid>347441af-9809-4df1-83ae-778ff62de7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes'])[1]/preceding::a[2]</value>
      <webElementGuid>34fbd6fb-5b9c-4f8d-8865-5e75e3f65724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fidelidad']/parent::*</value>
      <webElementGuid>47f584e0-598f-46f9-925b-b51ad3868260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Fidelidad/')]</value>
      <webElementGuid>ae43a568-4bbb-464d-a996-f51b62112eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td/a</value>
      <webElementGuid>3cee6c9f-8c3e-43ef-b0a7-a0bbd4a0414c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MenuLateral_repLista_ctl05_hypLink' and @href = '../Fidelidad/' and (text() = 'Fidelidad' or . = 'Fidelidad')]</value>
      <webElementGuid>9d85e305-292b-4b1a-8860-7bd2ac82bbed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
