<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sugerencia_atc</name>
   <tag></tag>
   <elementGuidId>b5b8eb28-8b0c-4a41-a090-5d24144dc3bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_MenuLateral_repLista_ctl04_repItens_ctl04_hypLinkItem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_MenuLateral_repLista_ctl04_repItens_ctl04_hypLinkItem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c7df3e3-abe9-4f62-be41-2abd769593d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MenuLateral_repLista_ctl04_repItens_ctl04_hypLinkItem</value>
      <webElementGuid>51fab479-5a6a-49a7-aef1-25b60e949765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>frmSugerencia.aspx</value>
      <webElementGuid>a14cf24f-23e3-4cf3-99b9-1134072d4e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sugerencia</value>
      <webElementGuid>d78a20da-3cd9-495a-83fe-6df859e8c734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_MenuLateral_repLista_ctl04_repItens_ctl04_hypLinkItem&quot;)</value>
      <webElementGuid>0606919a-8889-4383-90fa-5462e79a6e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ctl00_MenuLateral_repLista_ctl04_repItens_ctl04_hypLinkItem']</value>
      <webElementGuid>ed7c028a-ff99-4912-962f-277683a42711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/div[3]/table/tbody/tr/td/table[4]/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr[10]/td/a</value>
      <webElementGuid>9d0f84b7-e22b-41e0-8192-46dbb2cc40a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sugerencia')]</value>
      <webElementGuid>3b241e9e-d14b-4d44-ad83-b4da11caf18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Histórico PN'])[1]/following::a[1]</value>
      <webElementGuid>f5b40f9a-05ad-45d9-ae01-7a0f89d76053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extracto Usuario Cívica'])[1]/following::a[2]</value>
      <webElementGuid>0e1518fa-a61d-43bd-9567-f3bc55ce27fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fidelidad'])[1]/preceding::a[1]</value>
      <webElementGuid>cbf00122-ff0f-4e94-88ae-e9bb0757d507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registros'])[1]/preceding::a[2]</value>
      <webElementGuid>d914caf2-d66e-4cb5-8670-874895cffcd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sugerencia']/parent::*</value>
      <webElementGuid>0ddd5620-b385-4213-b853-fc3a71b7aaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'frmSugerencia.aspx')]</value>
      <webElementGuid>d7850f24-a9cd-4318-9c12-99a42f60badf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/a</value>
      <webElementGuid>95ca60b9-92f4-40c3-a34e-d13e259c1a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ctl00_MenuLateral_repLista_ctl04_repItens_ctl04_hypLinkItem' and @href = 'frmSugerencia.aspx' and (text() = 'Sugerencia' or . = 'Sugerencia')]</value>
      <webElementGuid>25234307-e5f7-4664-a6a9-d1723a65e6b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
