<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Inventario_atc</name>
   <tag></tag>
   <elementGuidId>3944fc77-d769-4e8e-ba8f-c711a693e5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_Header1_repModulos_ctl06_hypLink > em</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ctl00_Header1_repModulos_ctl06_hypLink']/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>890c5059-1391-4273-8a8a-94941fb5fdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventario</value>
      <webElementGuid>4cf7d9d9-a25a-4564-a466-50a7eb08be55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_Header1_repModulos_ctl06_hypLink&quot;)/em[1]</value>
      <webElementGuid>3db848a3-63c7-47ab-bcb4-abf902fc4290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_Header1_repModulos_ctl06_hypLink']/em</value>
      <webElementGuid>9ad86794-4a2b-40e6-9ba9-b417ce3cdf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emisión'])[1]/following::em[1]</value>
      <webElementGuid>f5acbf0e-8c00-4400-9b70-545912accb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compensación'])[1]/following::em[2]</value>
      <webElementGuid>07a315a5-4703-4230-a5ef-5ca17d2e2fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguridad'])[1]/preceding::em[1]</value>
      <webElementGuid>224490fd-a041-4989-8e90-e80f4cefb80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beneficios'])[1]/preceding::em[2]</value>
      <webElementGuid>05ace98d-c91c-4cf3-b9cf-fbb57a8033f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inventario']/parent::*</value>
      <webElementGuid>ceeace6e-c747-4981-91d9-1dac4f2da6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/em</value>
      <webElementGuid>72882a88-5195-4525-b382-c3cabf9ee483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Inventario' or . = 'Inventario')]</value>
      <webElementGuid>74016241-0808-4619-8454-72e5fdfc0e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
